apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-org2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer-org2
  template:
    metadata:
      labels:
        app: peer-org2
    spec:
      containers:
      - name: peer-org2-container
        image: hyperledger/fabric-peer:latest
        env:
        - name: CORE_PEER_ID
          value: "peer0.org2.example.com"
        - name: CORE_PEER_ADDRESS
          value: "peer0.org2.example.com:8051"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:8051"
        - name: CORE_PEER_CHAINCODEADDRESS
          value: "peer0.org2.example.com:8052"
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: "0.0.0.0:8052"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/msp/users/Admin@org2.example.com/msp" # Updated path
        volumeMounts:
        - name: msp-volume
          mountPath: /etc/hyperledger/msp
      volumes:
      - name: msp-volume
        hostPath:
          path: /Users/fernando/Projects/GithubProjects/OSC-IS/OSC-IS_Doc/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp  # Updated path
